apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - image: ogarokpeter/app-flask-redis:1.0.2
        name: app
        args:
        - python
        - app.py
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
status: {}
